name: summit2
description: Orbital Project
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  provider: ^4.1.2
  table_calendar: ^2.2.3
  firebase_helpers: ^0.1.8
  flutter_datetime_picker: ^1.3.8
  intl: ^0.15.8
  percent_indicator: ^2.1.5
  flutter_dynamic_icon: ^0.2.0+1
  flutter_webview_plugin: ^0.3.11
  oauth2: ^1.6.1
  dio: ^3.0.9
  flutter_local_notifications: ^1.4.4+2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+2
  path_provider: ^1.6.1
  http: ^0.12.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
